"""Locust load test for the Secure Notes application.

Drives realistic Next.js server-action traffic against a running stack
(``docker compose up -d``) and deliberately stresses the Valkey rate limiters
and the PostgreSQL connection pool.

Server actions are invoked via ``POST <page-url>`` with a ``Next-Action``
header (the current build's action id) and a ``text/plain`` body carrying the
React-Flight-serialized arguments as a JSON array.

Action ids are regenerated by the dev server on restart, so this file
discovers them at runtime from the server-reference manifest (mounted into
the repo via the web container's ``.:/app`` bind mount). If discovery fails
it falls back to constants matching the SEC-16 dev build.

Run from the repo root::

    pip install locust
    locust -f scripts/locustfile.py --host http://localhost:3000

Headless run::

    locust -f scripts/locustfile.py --host http://localhost:3000 \
        --headless -u 20 -r 2 --run-time 5m

While it runs, watch HTTP throughput, auth/note/cache counters and DB query
latency in the "Secure Notes Telemetry" Grafana dashboard.
"""

from __future__ import annotations

import json
import uuid
from datetime import datetime, timezone
from pathlib import Path

from locust import HttpUser, between, task
from locust.exception import StopUser

# ---------------------------------------------------------------------------
# Server-action id discovery
# ---------------------------------------------------------------------------

# Fallback constants matching the SEC-16 dev build.
_FALLBACK_ACTION_IDS: dict[str, str] = {
    "loginAction": "40703c3eb1cd6de69679e71a31eaf36362e1ec6073",
    "registerAction": "40c8f04a5e5d15258e8108a3f1116d1f7e3217d256",
    "logoutAction": "000b09762739d4372bd75492303ebff2f2fa5c4adb",
    "createNoteAction": "40ef429c6e0a8c878b534746046c8a6fde7d6ea376",
    "updateNoteAction": "40c1a39e96c37bdf22cdb7bd8d4d60491fc969878e",
}

_MANIFEST_CANDIDATES = [
    Path(".next/dev/server/server-reference-manifest.json"),
    Path(".next/server/server-reference-manifest.json"),
]


def _available_action_ids() -> dict[str, str]:
    ids = _FALLBACK_ACTION_IDS.copy()
    for manifest_path in _MANIFEST_CANDIDATES:
        if not manifest_path.exists():
            continue
        try:
            manifest = json.loads(manifest_path.read_text("utf-8"))
        except (OSError, ValueError):
            continue
        for action_id, meta in (manifest.get("node") or {}).items():
            exported = meta.get("exportedName")
            if exported:
                ids[exported] = action_id
        break
    return ids


class _ActionIdStore:
    """Lazily resolves the current build's server-action ids.

    Turbopack regenerates ids on every (re)compile of a page that uses server
    actions, which in dev happens on-demand — so the manifest can appear after
    the locust process has already started. Resolving per request (cache keyed
    on the manifest mtime) means the probe keeps working even mid-run.
    """

    def __init__(self) -> None:
        self._ids: dict[str, str] = _FALLBACK_ACTION_IDS.copy()
        self._mtime_ns: int | None = None

    def _refresh(self) -> None:
        best = next((m for m in _MANIFEST_CANDIDATES if m.exists()), None)
        if best is None:
            return
        try:
            mtime_ns = best.stat().st_mtime_ns
        except OSError:
            return
        if mtime_ns == self._mtime_ns:
            return
        try:
            manifest = json.loads(best.read_text("utf-8"))
        except (OSError, ValueError):
            return
        ids = self._ids.copy()
        for action_id, meta in (manifest.get("node") or {}).items():
            exported = meta.get("exportedName")
            if exported:
                ids[exported] = action_id
        self._ids = ids
        self._mtime_ns = mtime_ns

    def get(self, name: str) -> str | None:
        self._refresh()
        return self._ids.get(name)


ACTION_IDS = _ActionIdStore()

if not any(m.exists() for m in _MANIFEST_CANDIDATES):
    print(
        "[locust] server-reference manifest not found yet; starting from fallback "
        "action ids. They will be refreshed automatically from the manifest as "
        "soon as the dev server compiles the action pages."
    )


# ---------------------------------------------------------------------------
# Response decoding + request helpers
# ---------------------------------------------------------------------------


def rsc_result(body: str) -> dict | None:
    """Extract the JSON result row from a Next.js RSC action response.

    A successful action streams a flight payload whose rows are
    ``<hex>:<json>``, notably ``1:{"success":true,"note":{...}}`` or
    ``1:{"success":false,"error":"Too many attempts. ..."}``.
    """
    if not body:
        return None
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped.startswith("1:") and not stripped.startswith("2:"):
            continue
        candidate = stripped[2:]
        try:
            return json.loads(candidate)
        except (ValueError, IndexError):
            continue
    return None


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def post_action(
    http_user: HttpUser,
    action: str,
    url: str,
    args: dict | list,
) -> dict | None:
    """POST a server action; returns the parsed result or None on failure.

    Also fires a synthetic rate-limit failure (visible in the locust report)
    whenever the Valkey rate limiter answers.

    The dev server regenerates action ids on demand. If a request comes back
    with ``Failed to find Server Action ... older or newer deployment`` we
    re-resolve the id from the manifest and retry once so the probe is robust
    to stale ids mid-run.
    """

    def issue(action_id: str):
        return http_user.client.request(
            "POST",
            url,
            headers={
                "Next-Action": action_id,
                "Content-Type": "text/plain;charset=UTF-8",
            },
            data=json.dumps(
                [args] if isinstance(args, dict) else args,
                separators=(",", ":"),
            ),
            name=url,
            catch_response=True,
        )

    action_id = ACTION_IDS.get(action)
    if not action_id:
        raise StopUser(f"missing action id for {action}")

    with issue(action_id) as resp:
        result = rsc_result(resp.text)
        stale_id = (
            resp.status_code == 200
            and result is None
            and "Failed to find Server Action" in resp.text
        )
        if stale_id:
            fresh_id = ACTION_IDS.get(action)
            if fresh_id and fresh_id != action_id:
                resp.failure("stale action id; retried")
                with issue(fresh_id) as retry:
                    result = rsc_result(retry.text)
                    rate_limited = bool(
                        result and "Too many attempts" in str(result.get("error", ""))
                    )
                    if rate_limited:
                        retry.failure("rate limited (expected)")
                        return None
                    if retry.status_code != 200:
                        retry.failure(str(retry.status_code))
                        return None
                    retry.success()
                    return result
            resp.failure("stale action id")
            return None

        rate_limited = bool(
            result and "Too many attempts" in str(result.get("error", ""))
        )
        if rate_limited:
            resp.failure("rate limited (expected)")
            return None
        if resp.status_code != 200:
            resp.failure(str(resp.status_code))
            return None
        resp.success()
        return result


# ---------------------------------------------------------------------------
# User classes
# ---------------------------------------------------------------------------


class SecureNotesUser(HttpUser):
    """Realistic journey: register ONCE, then repeatedly log in and churn notes."""

    wait_time = between(1, 5)
    weight = 4

    def on_start(self) -> None:
        self.email = f"locust-{uuid.uuid4().hex[:12]}@example.com"
        self.password = "LocustPass1!"
        self.registered = False

    @task
    def full_journey(self) -> None:
        # Register only once per user. Registering repeatedly with the same
        # email after a successful sign-up would otherwise be 307-redirected by
        # the auth-route guard (once a session cookie exists) and never reach
        # the register action / rate limiter.
        if not self.registered:
            registered = post_action(
                self, "registerAction", "/register",
                {"email": self.email, "password": self.password},
            )
            if not registered:
                # Shared host IP may already be throttled by the probe class.
                return
            self.registered = True

        # Logout, then log back in to exercise password verification + login limiter.
        post_action(self, "logoutAction", "/notes", [])
        self.client.get("/login", name="/login (page)")
        logged_in = post_action(
            self, "loginAction", "/login",
            {"email": self.email, "password": self.password},
        )
        if not logged_in:
            return

        # Heavy DB churn: create notes and force autosave + manual snapshots.
        for _ in range(3):
            created = post_action(
                self, "createNoteAction", "/notes",
                {"title": f"Locust note {uuid.uuid4().hex[:6]}", "content": "Seed content"},
            )
            note_id = ((created or {}).get("note") or {}).get("id")
            if not note_id:
                continue

            post_action(
                self, "updateNoteAction", f"/notes/{note_id}",
                {
                    "id": note_id,
                    "title": f"Autosaved {uuid.uuid4().hex[:6]}",
                    "content": "Autosave body.",
                    "clientUpdatedAt": utc_now_iso(),
                    "isManualSave": False,
                },
            )
            post_action(
                self, "updateNoteAction", f"/notes/{note_id}",
                {
                    "id": note_id,
                    "title": "Manual save",
                    "content": "Final body.",
                    "clientUpdatedAt": utc_now_iso(),
                    "isManualSave": True,
                },
            )

        self.client.get("/notes", name="/notes (page)")


class RateLimitProbeUser(HttpUser):
    """Deliberately hammer the rate-limited endpoints to force Valkey 429s."""

    wait_time = between(1, 5)
    weight = 1

    def on_start(self) -> None:
        self.email = f"probe-{uuid.uuid4().hex[:8]}@example.com"
        self.password = "ProbePass1!x"  # wrong on purpose: always fails login

    @task
    def hammer_login(self) -> None:
        # Wrong credentials against a fixed email so every attempt reaches the
        # login action (never a redirect), failing auth and incrementing the
        # (ip:email) bucket until Valkey answers with "Too many attempts".
        post_action(
            self, "loginAction", "/login",
            {"email": self.email, "password": self.password},
        )

    @task
    def hammer_register(self) -> None:
        # Clear the session so the proxy never 307-redirects an authenticated
        # client away from /register; the register action (and its IP bucket)
        # then runs every time. A fresh email each attempt keeps the system
        # from short-circuiting on a duplicate-email response for the probe.
        self.client.cookies.clear()
        fresh_email = f"probe-{uuid.uuid4().hex[:10]}@example.com"
        post_action(
            self, "registerAction", "/register",
            {"email": fresh_email, "password": "ProbePass1!"},
        )